import sys
import json
import subprocess
from datetime import datetime, timezone
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parent.parent
TASK_FILE = PROJECT_ROOT / "automation" / "CURRENT_TASK.md"
EVENTS_FILE = PROJECT_ROOT / "automation" / "events.jsonl"

AGY_EXE = Path(
    r"C:\Users\Admin\AppData\Local\agy\bin\agy.exe"
)

WORKSPACE = PROJECT_ROOT


def utc_now():
    return datetime.now(timezone.utc).isoformat()


def write_event(event):
    EVENTS_FILE.parent.mkdir(parents=True, exist_ok=True)

    with EVENTS_FILE.open("a", encoding="utf-8") as f:
        f.write(json.dumps(event, ensure_ascii=False) + "\n")


def run_executor_bridge():
    print("=== ANTIGRAVITY EXECUTOR BRIDGE START ===")

    # -------------------------------------------------
    # 1. Validate environment
    # -------------------------------------------------

    if not TASK_FILE.exists():
        print(f"[-] ERROR: Task file not found: {TASK_FILE}")
        sys.exit(1)

    if not AGY_EXE.exists():
        print(f"[-] ERROR: agy.exe not found: {AGY_EXE}")
        sys.exit(1)

    print(f"[+] Workspace : {WORKSPACE}")
    print(f"[+] Task      : {TASK_FILE}")
    print(f"[+] AGY       : {AGY_EXE}")

    # -------------------------------------------------
    # 2. Read task generated by ChatGPT
    # -------------------------------------------------

    task_prompt = TASK_FILE.read_text(encoding="utf-8").strip()

    if not task_prompt:
        print("[-] ERROR: CURRENT_TASK.md is empty.")
        sys.exit(1)

    print(f"[+] Task loaded ({len(task_prompt)} characters).")

    # -------------------------------------------------
    # 3. Record dispatch
    # -------------------------------------------------

    write_event({
        "timestamp": utc_now(),
        "event": "EXECUTOR_DISPATCHED",
        "executor": "ANTIGRAVITY_AGY",
        "status": "RUNNING"
    })

    # -------------------------------------------------
    # 4. Build safe Antigravity prompt
    # -------------------------------------------------

    safety_header = f"""
You are the implementation worker for this repository.

WORKSPACE:
{WORKSPACE}

RULES:
- Work only inside the workspace above.
- Follow AGENTS.md and repository specifications.
- Perform only the task below.
- Do not decide or start another phase.
- Do not modify files outside the workspace.
- Prefer direct file editing tools.
- Do not use destructive commands.
- Do not use dangerously-skip-permissions.
- When finished, report what you changed and any tests performed.

TASK FROM CHATGPT:

"""

    full_prompt = safety_header + task_prompt

    # -------------------------------------------------
    # 5. Execute Antigravity through official AGY CLI
    # -------------------------------------------------

    args = [
        str(AGY_EXE),
        f"--add-dir={WORKSPACE}",
        "--mode",
        "accept-edits",
        "--output-format",
        "json",
        f"--print={full_prompt}",
    ]

    print("[*] Dispatching task to Antigravity...")

    try:
        result = subprocess.run(
            args,
            cwd=str(WORKSPACE),
            capture_output=True,
            text=True,
            timeout=1800,
            shell=False,
        )

    except subprocess.TimeoutExpired:
        print("[-] ERROR: Antigravity timed out.")

        write_event({
            "timestamp": utc_now(),
            "event": "EXECUTOR_COMPLETED",
            "executor": "ANTIGRAVITY_AGY",
            "status": "TIMEOUT"
        })

        sys.exit(1)

    except Exception as exc:
        print(f"[-] ERROR launching Antigravity: {exc}")

        write_event({
            "timestamp": utc_now(),
            "event": "EXECUTOR_COMPLETED",
            "executor": "ANTIGRAVITY_AGY",
            "status": "ERROR",
            "error": str(exc)
        })

        sys.exit(1)

    # -------------------------------------------------
    # 6. Show Antigravity result
    # -------------------------------------------------

    if result.stdout:
        print("\n=== ANTIGRAVITY OUTPUT ===")
        print(result.stdout)

    if result.stderr:
        print("\n=== ANTIGRAVITY STDERR ===")
        print(result.stderr)

    # -------------------------------------------------
    # 7. Record result
    # -------------------------------------------------

    if result.returncode != 0:
        write_event({
            "timestamp": utc_now(),
            "event": "EXECUTOR_COMPLETED",
            "executor": "ANTIGRAVITY_AGY",
            "status": "FAILED",
            "returncode": result.returncode
        })

        print(
            f"[-] Antigravity failed with return code "
            f"{result.returncode}."
        )

        sys.exit(result.returncode)

    write_event({
        "timestamp": utc_now(),
        "event": "EXECUTOR_COMPLETED",
        "executor": "ANTIGRAVITY_AGY",
        "status": "SUCCESS",
        "returncode": result.returncode
    })

    print("[+] Antigravity execution completed successfully.")
    print("=== ANTIGRAVITY EXECUTOR BRIDGE END ===")


if __name__ == "__main__":
    run_executor_bridge()